name: core-analysis
channels:
  - conda-forge
dependencies:
  - python=3.7.*
  - cython
  - segmentation-models
  - pydensecrf
  - imgaug
  - pycocotools
  - pillow
  - tensorflow=2.11.0
  - opencv-python
  - numpy
  - h5py
  - inflection