name: core-analysis
channels:
  - conda-forge
dependencies:
  - python=3.7.16
  - conda-build
  - cython
  - segmentation-models
  - pydensecrf
  - imgaug
  - pycocotools
  - pillow
  - tensorflow=2.11.0
  - opencv-python
  - numpy
  - h5py
  - inflection
  - dvc=2.10.2
  - fsspec=2022.11.0