name: model-testing
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7.16
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --location $CML --output /bin/cml
          chmod 755 /bin/cml

          dvc remote add data gdrive://1SSuE4GVQ5xjePujH0AGdXBVWXauanteG
          dvc remote add images gdrive://1iYyv9QR9NK7XXVaN4IzFAtQPgDWdYYlY
          dvc pull data
          dvc pull images

          pip install -e .
          python core_analysis --train --test --do-augment

          cat metrics.txt >> report.md
          echo "![](./plot.png)" >> report.md
          cml comment create report.md